Boot.Web/ViewModels/SetupViewModel.cs
using Boot.Multitenancy.Intrastructure.Domain;
using Boot.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;

namespace Boot.Web.ViewModels
{ 
    public class SetupViewModel
    {
        public List<Type> GetTypes{ get{ return GetInstalledTypes(); } }
        public List<string> EntityNames { get; set; }
        public string SiteName { get; set; }
        public string FooterText { get; set; }
        public string Connectionstring { get; set; }
        public List<DbType> DbTypes { get; set; }
        public DbType SelectedType { get; set; }


        public SetupViewModel()
        {
            EntityNames = new List<string>();
            DbTypes = new List<DbType> { DbType.MySql5, DbType.SqlCe, DbType.SqlServer2008 };
        }

        /// <summary>
        /// Grab all installed types by Fluent
        /// </summary>
        /// <returns>A list of name of the types.</returns>
        public List<Type> GetInstalledTypes()
        {
            var Types = new List<Type>();

            foreach (var assemblyName in Assembly.GetExecutingAssembly().GetReferencedAssemblies())
            {
                var assembly = Assembly.Load(assemblyName);
                foreach (var type in assembly.GetTypes())
                {
                    if (type.IsClass && (type.GetInterface("IEntity") != null) && (!type.IsAbstract))
                    {
                        Types.Add(type);
                    }
                }
            }
            return Types;
        }
    }
}

Boot.Web/Controllers/SetupController.cs
#define DEBUG
#define TRACE
#undef TRACE

using Boot.Web.Models;
using Boot.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlServerCe;
using System.Data.SqlClient;

namespace Boot.Web.Controllers
{
    public class SetupController : Controller
    {

        SetupViewModel Model { get; set; }

        public SetupController()
        {
            Model = new SetupViewModel();
        }


        public ActionResult Index()
        {
            return View(Model);
        }


        [HttpPost]
        public ActionResult Index(SetupViewModel model)
        {
            Model.EntityNames.AddRange(model.EntityNames);

            dynamic con = null;

            switch (model.SelectedType)
            {
                case DbType.SqlCe:
                    con = new SqlCeConnection(model.Connectionstring);
                    break;
                case DbType.MySql5:
                    //con = new MySql.Data.MySqlClient.MySqlConnection(model.Connectionstring);
                    break;
                case DbType.SqlServer2008:
                    con = new SqlConnection(model.Connectionstring);
                    break;
            }


#if debug
            dynamic ex = null;
            try{ con.Open(); } catch(Exception e)  {
                ex = e;
                goto TypeErrorDebug;
            }

            TypeErrorDebug: ModelState.AddModelError("Connectionstring", "The connectionstring seems invalid.\n" + ex.Message);
#else

            try { con.Open(); }
            catch
            {
                goto TypeError;
            }

//#line 48 "Error"
        TypeError: ModelState.AddModelError("Connectionstring", "The connectionstring seems invalid.\n");
#endif

            //#warning debug is defined at line 56

            return View(model);
        }

        public ActionResult Finish()
        {
            return View();
        }
    }
} 

Boot.Web/Views/Setup/Index.cshtml
@model Boot.Web.ViewModels.SetupViewModel
@{Layout = null;}

<!DOCTYPE html>
<html>
<head>
    <title>Setup</title>
    <link rel="stylesheet" type="text/css" href="/Content/Bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/Content/Setup.css" />
    <script type="text/javascript" src="/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/Scripts/bootstrap.js"></script>
</head>
<body>


    @using (Html.BeginForm("index", "Setup", FormMethod.Post, new { role = "form" }))
    {
        @Html.ValidationSummary(true)

        <div class="container">
            <div class="row">
                <div class="col-lg-12">&nbsp;</div>
            </div>
            <div class="row">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-8">
                    <h1>WebSite setup</h1>
                    <p>Welcome to the site setup. By default we setup one page and site setting for you. It's important that you create the database correct, because you must change this manually if something is wrong. Note! The Settings table is required.</p>
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#home" data-toggle="tab">Website settings</a></li>
                        <li><a href="#database" data-toggle="tab">Database</a></li>
                        <li><a href="#profile" data-toggle="tab">Tables</a></li>
                        <li><a href="#dns" data-toggle="tab">Host header values</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="home">
                            <div class="input-group">
                                <span class="input-group-addon">Site name</span>
                                @Html.TextBoxFor(m => m.SiteName, new { @class = "form-control", placeholder = "Your website name." })
                                @Html.ValidationMessageFor(m => m.SiteName)
                            </div>
                            <br />
                            <div class="input-group">
                                <span class="input-group-addon">Footer</span>
                                @Html.TextBoxFor(m => m.FooterText, new { @class = "form-control", placeholder = "Footer text." })
                                @Html.ValidationMessageFor(m => m.FooterText)
                            </div>
                        </div>
                        <div class="tab-pane" id="profile">
                            <div class="form-group">
                                <span>Select tables to install</span>
                                @Html.ListBoxFor(model => model.EntityNames,
                                    new SelectList(Model.GetTypes, "FullName", "Name"), new { multiple = "multiple", rows = 10, style = "width:200px", @class = "form-control" })
                            </div>
                        </div>
                        <div class="tab-pane" id="database">

                            <div class="input-group">
                                <span class="input-group-addon">Database type</span>
                                @Html.DropDownListFor(model => model.SelectedType, new SelectList(Model.DbTypes, "", ""), new { @class = "form-control" })
                            </div>
                            <br />

                            <div class="input-group">
                                <span class="input-group-addon">Connectionstring</span>
                                @Html.TextBoxFor(m => m.Connectionstring, new { @class = "form-control", placeholder = "For eg. Mysql: Server=127.0.0.1;Port=3306;Database=BootTestData;Uid=boots;Pwd=boots;" })
                                @Html.ValidationMessageFor(m => m.Connectionstring)
                            </div>
                            <br/>
                            <div class="input-group">
                                <span class="input-group-addon">Database name</span>
                                <input type="text" name="DatabaseName" class="form-control" placeholder="Enter database name" />
                            </div>

                        </div>
                        <div class="tab-pane" id="dns">
                            <div class="form-group">
                                <span class="input-group-addon">Existing website collection</span>
                                @**Html.DropDownListFor(model => model.SelectedSite, new SelectList(Model.Sites, "", ""), new { @class = "form-control" })*@
                               
                                 <input type="text" class="form-control" id="hostval" placeholder="Type in a hostname, for eg. www.boot.com">
                                <br />
                                <select size="10" class="form-control" id="HostValues"></select>
                                <br />
                                <button type="button" id="btnAdd" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-plus-sign"></span> Add
                                </button>&nbsp;
                                <button type="button" id="btnRemove" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-minus-sign"></span> Remove
                                </button>
                            </div>
                        </div>
                        <br/>

                        <button type="button" id="btnSave" class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-arrow-right"></span> Save
                        </button>
                    </div>
                    <div class="col-lg-2"></div>
                </div>
            </div>
        </div>
        <script>

            $('#hostval').focus(function () {
                $(document).keydown(function (event) {
                    if (event.which === 13) {
                        $("#btnAdd").trigger("click");
                    }
                });
            });




            

            $("#btnAdd").click(function () {
                var dns = $("#hostval").val();
                if (dns == '')
                    return;
                var has = false;
                $("#HostValues").each(function () {
                    if ($(this).val() == dns) {
                        has = true;
                    }
                });
                if (has == false) {
                    $('#HostValues').prepend(new Option(dns, dns, true, true));
                    $("#hostval").val('');
                    has = false;
                }
            });

            $("#btnRemove").click(function () {
                var dns = $("#HostValues").val()
                if (dns == '')
                    return;
                $('#HostValues option').each(function () {
                    if ($(this).val() == dns) {
                        $(this).remove();
                    }
                });
            });

            $("#HostValues").click(function () {
                $("#hostval").val($(this).val());
            });
        </script>
    }

    @Scripts.Render("~/bundles/jqueryval")
</body>







</html>